Metrics/ParameterLists:
  Max: 6

Metrics/MethodLength:
  Max: 20

Naming/UncommunicativeMethodParamName:
  MinNameLength: 1

Metrics/AbcSize:
  Max: 25

AllCops:
  Exclude:
    - "PracticeRuby/ruby_34_strings.rb"