language: ruby
rvm:
 - 2.4
 - 2.5

# cache:
#  - bundler

script: 
 - bundle exec rake
 - bundle exec rubocop 

notifications:
  email:
    on_success: never
    on_failure: never
    
# before_install:
#  - gem install bundler